name: Build Website

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build Website
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v4

      - name: Set Up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 11

      - name: Set Up Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Check Website
        run: pnpm check

      - name: Build Website
        run: pnpm build

      - name: Verify Installer
        run: cmp install.sh dist/install.sh

      - name: Deploy
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: silitics/actions/deploy-site@main
        with:
          domain: tascarrel.dev
          source-dir: dist
          s3-access-key: ${{ vars.SILITICS_SITES_ACCESS_KEY }}
          s3-secret-key: ${{ secrets.SILITICS_SITES_SECRET_KEY }}
